name: Markdownlint (All files)

on:
  pull_request:
    branches:
      - main
    paths:
      - .markdownlint-cli2.jsonc
      - .nvmrc
      - .prettier*
      - package.json
      - yarn.lock
      - .github/workflows/markdown-lint.yml
      - .github/workflows/markdownlint-problem-matcher.json

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v28.0.0
        with:
          files: |
            **/*.md
          
      - name: Setup Node.js environment
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install all yarn packages
        run: yarn --frozen-lockfile

      - name: Lint markdown files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
          yarn lint:md
          yarn lint:fm
